# Generated by Django 4.0 on 2021-12-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='address',
            field=models.TextField(default='address'),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='crusine',
            field=models.TextField(default='crusine'),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='description',
            field=models.TextField(default='description'),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='links',
            field=models.TextField(default='links'),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='mean_prices',
            field=models.TextField(default='mean_prices'),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='name',
            field=models.TextField(default='name'),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='neighborhood',
            field=models.TextField(default='neighborhood'),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='picture',
            field=models.TextField(default='picture'),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='time',
            field=models.TextField(default='time'),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='type_of_meal',
            field=models.TextField(default='type_of_meal'),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='type_of_restaraunt',
            field=models.TextField(default='type_of_restaraunt'),
        ),
    ]
